# Site settings
default_title: Sigler Design
title_after: The UX Portfolio of Michael Sigler
email: mikesigler@gmail.com
author: Michael Sigler
site-name: Sigler Design
description: > # this means to ignore newlines until "baseurl:"
  Michael Sigler is a designer in Portland, OR.
  He is a craftman, a maker and a problem solver
  finding helpful ways to enrich and better a
  user's experience.
baseurl: "" # the subpath of your site, e.g. /blog
hosted_url: "http://siglerdesign.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: michaelsigler
github_username:  mikesigler

# Build settings
markdown: kramdown
# theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
